/**
 * copy.md §4–§5 string tables, wired 1:1 (PRD §3: "all user-facing strings are
 * the keys in copy.md §4–§5, wired 1:1 by the FE"). This is the SINGLE source of
 * truth for strings — no copy lives in components. Interpolation slots ({n},
 * {seconds}, {token}, {mock_url}, …) are filled via the `t()` helper.
 *
 * Keys are verbatim from copy.md. Do not paraphrase a value here; a changed
 * string is a copy edit against copy.md.
 */
export const copy = {
  // ── 4.1 Landing ──
  'landing.brand.wordmark': 'HookBox',
  'landing.brand.markAlt': 'HookBox',
  'landing.hero.headline': 'Mock, intercept, and watch HTTP — live.',
  'landing.hero.subhead':
    'Self-hosted API mocking and request interception with a real-time inspector. One email in, one endpoint out. No password, no setup.',
  'landing.email.label': 'Email address',
  'landing.email.placeholder': 'you@company.com',
  'landing.email.submit': 'Get my endpoint',
  'landing.email.submitting': 'Setting up…',
  'landing.email.helper':
    'Your email is the recovery key — no password. Re-enter it any time to pick up where you left off.',
  'landing.strip.mock.title': 'Mock',
  'landing.strip.mock.body':
    'Spin up a mock URL instantly. Define rules by method, path, headers, and body — return exactly the response you want.',
  'landing.strip.intercept.title': 'Intercept',
  'landing.strip.intercept.body':
    "Point an endpoint at a real upstream and proxy what you don't mock. Add latency, rate limits, and chaos to see how your client copes.",
  'landing.strip.inspect.title': 'Inspect',
  'landing.strip.inspect.body':
    'A streaming feed of every hit with a deep inspector — headers, query, body, the response served, and the full resolution trace.',
  'landing.cli.link': 'Already have an endpoint? Tunnel from your machine →',
  'landing.footer.tagline':
    "Self-hosted · Single binary · No tracking — built for developers who'd rather run it themselves.",
  // ── 4.2 Landing states ──
  'landing.error.email.invalid': 'Enter a valid email address.',
  'landing.error.rateLimit': 'Too many attempts. Try again in {seconds}s.',
  'landing.error.network': "Couldn't reach the server. Check your connection and try again.",
  'landing.error.noEndpoint':
    'Session created, but no endpoint came back. Try again — if it persists, restart the server.',
  'landing.warn.storage':
    "This browser won't remember your session (private mode or storage blocked). You can still continue — keep your email to return.",
  'landing.error.generic': "Something didn't go through. Try again.",

  // ── 5.1 App shell & nav ──
  'shell.skipLink': 'Skip to content',
  'shell.nav.endpointSwitcher.label': 'Switch endpoint',
  'shell.nav.endpointSwitcher.placeholder': 'Select an endpoint',
  'shell.nav.newEndpoint': 'New endpoint',
  'shell.nav.newEndpoint.aria': 'Create a new endpoint',
  'shell.nav.theme.aria': 'Toggle theme',
  'shell.account.label': 'Account',
  'shell.account.signedInAs': 'Signed in as {email}',
  'shell.account.signOut': 'Sign out',
  'shell.account.signOut.confirmTitle': 'Sign out?',
  'shell.account.signOut.confirmBody':
    'This clears your secret from this browser. Re-enter your email to return.',
  'shell.account.signOut.confirm': 'Sign out',
  'shell.mobileNav.open.aria': 'Open menu',
  'shell.mobileNav.title': 'Menu',

  // ── 5.2 Dashboard sub-header ──
  'dash.mockUrl.label': 'Mock URL',
  'dash.mockUrl.copy.aria': 'Copy mock URL',
  'dash.pathUrl.label': 'Local path',
  'dash.pathUrl.copy.aria': 'Copy local path',
  'dash.autoCrud.label': 'Auto-CRUD',
  'dash.autoCrud.tooltip': 'Serve a REST store for unmatched requests.',
  'dash.action.rules': 'Rules',
  'dash.action.newRule': 'New rule',
  'dash.action.settings': 'Settings',
  'dash.tunnel.active': 'Tunnel connected',
  'dash.tunnel.active.tooltip': 'A tunnel is forwarding this endpoint to a local machine.',

  // ── 5.3 Feed ──
  'feed.header.title': 'Live feed',
  'feed.pause': 'Pause',
  'feed.resume': 'Resume',
  'feed.pause.aria': 'Pause the live feed',
  'feed.resume.aria': 'Resume the live feed',
  'feed.newCount': '{n} new',
  'feed.newCount.aria': '{n} new requests — click to show',
  'feed.count': 'Showing {n} of last 100',
  'feed.loading.aria': 'Loading recent requests',
  'feed.empty.title': 'No requests yet',
  'feed.empty.body': 'Send a request to your mock URL and it shows up here, live.',
  'feed.empty.sampleLabel': 'Try it',
  'feed.empty.sampleHint': 'Run this in a terminal — or just open the URL in a browser.',
  'feed.empty.sample': 'curl {mock_url}/ping',
  'feed.row.servedBy.aria': 'Served by {servedBy}',
  'feed.row.latency': '{ms}ms',
  'feed.row.select.aria': 'Inspect {method} {path}, {status}',

  // ── 5.4 Connection pill ──
  'feed.conn.connecting': 'Connecting…',
  'feed.conn.live': 'Live',
  'feed.conn.reconnecting': 'Reconnecting…',
  'feed.conn.reconnecting.n': 'Reconnecting… (try {n})',
  'feed.conn.sse': 'Live (SSE)',
  'feed.conn.sse.tooltip': 'WebSocket unavailable — streaming over SSE instead. Same events.',
  'feed.conn.offline': 'Offline',
  'feed.conn.offline.tooltip': 'Lost connection to the feed. Showing the last requests received.',
  'feed.conn.unauthorized': 'Not authorized for this feed',
  'feed.conn.unauthorized.tooltip':
    'Your secret no longer authorizes this feed. It may have been rotated elsewhere.',
  'feed.conn.busy': 'Feed busy',
  'feed.conn.busy.tooltip':
    "Too many connections to this endpoint's feed ({max} max). Close another tab and it'll reconnect.",

  // ── 5.5 Inspector ──
  'insp.empty.title': 'Select a request',
  'insp.empty.body': 'Pick a request on the left to inspect it.',
  'insp.loading.aria': 'Loading request detail',
  'insp.pending.title': 'Detail on its way',
  'insp.pending.body': "This request just landed — its detail is still being written.",
  'insp.pending.retry': 'Retry',
  'insp.error.title': "Couldn't load this request",
  'insp.error.body': 'Something went wrong fetching the detail.',
  'insp.error.retry': 'Retry',
  'insp.unauthorized.title': 'Not authorized',
  'insp.unauthorized.body':
    "Your secret doesn't authorize this request. Re-enter your email to continue.",
  'insp.tab.headers': 'Headers',
  'insp.tab.query': 'Query',
  'insp.tab.body': 'Body',
  'insp.tab.response': 'Response Served',
  'insp.tab.trace': 'State & Tracing',
  'insp.headers.empty': 'No headers.',
  'insp.headers.redacted': 'redacted',
  'insp.headers.redacted.tooltip':
    'Sensitive headers (your secret, Cookie, Authorization) are never stored.',
  'insp.query.empty': 'No query parameters.',
  'insp.body.empty': 'No request body.',
  'insp.body.binary': 'Binary body — not shown.',
  'insp.body.truncated': 'Truncated at {bytes} — captured bodies are capped.',
  'insp.body.pretty': 'Pretty',
  'insp.body.raw': 'Raw',
  'insp.body.expandAll': 'Expand all',
  'insp.body.collapseAll': 'Collapse all',
  'insp.body.copy': 'Copy body',
  'insp.response.servedByLabel': 'Served by',
  'insp.response.headers': 'Response headers',
  'insp.response.body': 'Response body',
  'insp.response.empty': 'No response body.',
  'insp.trace.title': 'Resolution trace',
  'insp.trace.empty': 'No trace steps.',
  'insp.trace.stateTitle': 'State at request time',
  'insp.trace.stateEmpty': 'No state set on this endpoint.',
  'insp.trace.latency': 'Applied latency: {applied}ms of {total}ms total',

  // ── 5.6 Served-by chip labels & tooltips ──
  'servedBy.rule.label': 'rule',
  'servedBy.rule.tooltip': 'Matched a rule you wrote.',
  'servedBy.crud.label': 'crud',
  'servedBy.crud.tooltip': 'Served by Auto-CRUD.',
  'servedBy.mitm.label': 'mitm',
  'servedBy.mitm.tooltip': 'Proxied to your upstream target.',
  'servedBy.tunnel.label': 'tunnel',
  'servedBy.tunnel.tooltip': 'Forwarded down your tunnel to localhost.',
  'servedBy.default.label': 'default',
  'servedBy.default.tooltip': "No rule matched — the endpoint's default response.",
  'servedBy.cors.label': 'cors',
  'servedBy.cors.tooltip': 'An Auto-CORS preflight response.',
  'servedBy.chaos.label': 'chaos',
  'servedBy.chaos.tooltip': 'A failure injected by chaos.',
  'servedBy.ratelimit.label': 'ratelimit',
  'servedBy.ratelimit.tooltip': 'Rejected by the rate limit.',

  // ── 5.7 Rule builder ──
  'rule.new.title': 'New rule',
  'rule.edit.title': 'Edit rule',
  'rule.field.name.label': 'Name',
  'rule.field.name.placeholder': 'e.g. Login success',
  'rule.field.name.helper': 'Optional. Just for you — shows in the rules list.',
  'rule.field.priority.label': 'Priority',
  'rule.field.priority.helper': 'Lower wins. Ties break by creation order.',
  'rule.field.enabled.label': 'Enabled',
  'rule.tab.matching': 'Matching',
  'rule.tab.response': 'Response',
  'rule.tab.templating': 'Templating',
  'rule.tab.actions': 'Actions',
  'rule.tab.throttling': 'Throttling',
  'rule.cancel': 'Cancel',
  'rule.save': 'Save rule',
  'rule.saving': 'Saving…',
  'rule.match.method.label': 'Method',
  'rule.match.method.any': 'ANY',
  'rule.match.path.label': 'Path',
  'rule.match.path.placeholder': '/users/:id',
  'rule.match.path.helper': 'Use :name to capture a segment and /* to match the rest. Exact otherwise.',
  'rule.match.path.captured': 'Captures: {names}',
  'rule.match.headers.label': 'Required headers',
  'rule.match.headers.helper': 'Request must include these. Names are case-insensitive.',
  'rule.match.headers.keyPlaceholder': 'Header name',
  'rule.match.headers.valPlaceholder': 'Expected value',
  'rule.match.query.label': 'Required query params',
  'rule.match.query.keyPlaceholder': 'Param',
  'rule.match.query.valPlaceholder': 'Expected value',
  'rule.match.body.label': 'Body conditions',
  'rule.match.body.helper': 'Test the JSON body by path.',
  'rule.match.body.pathPlaceholder': '$.user.role',
  'rule.match.body.op.eq': 'equals',
  'rule.match.body.op.neq': 'not equals',
  'rule.match.body.op.contains': 'contains',
  'rule.match.body.op.exists': 'exists',
  'rule.match.body.valPlaceholder': 'Value',
  'rule.match.state.label': 'State requirements',
  'rule.match.state.helper': "Match only when the endpoint's state holds.",
  'rule.match.state.keyPlaceholder': 'State key',
  'rule.match.state.op.eq': 'equals',
  'rule.match.state.op.neq': 'not equals',
  'rule.match.state.op.exists': 'exists',
  'rule.match.state.op.absent': 'absent',
  'rule.match.state.valPlaceholder': 'Value',
  'rule.match.addRow': 'Add',
  'rule.match.removeRow.aria': 'Remove row',
  'rule.resp.status.label': 'Status code',
  'rule.resp.status.helper': '100–599.',
  'rule.resp.contentType.label': 'Content-Type',
  'rule.resp.headers.label': 'Response headers',
  'rule.resp.body.label': 'Response body',
  'rule.resp.body.placeholder': '{ "id": "{{random \'uuid\'}}" }',
  'rule.resp.body.counter': '{used} / 256 KB',
  'rule.resp.body.counter.over': "{used} / 256 KB — over the cap, this rule won't render",
  'rule.tmpl.intro': 'Click a tag to insert it at your cursor in the response body.',
  'rule.tmpl.honesty': 'Unknown tags are left exactly as written — they never error.',
  'rule.tmpl.group.time': 'Time',
  'rule.tmpl.group.random': 'Random',
  'rule.tmpl.group.request': 'Request',
  'rule.tmpl.group.state': 'State',
  'rule.tmpl.tag.now.iso': "{{now 'iso'}}",
  'rule.tmpl.tag.now.unix': "{{now 'unix'}}",
  'rule.tmpl.tag.random.uuid': "{{random 'uuid'}}",
  'rule.tmpl.tag.random.int': "{{random 'int' 1 100}}",
  'rule.tmpl.tag.request.path': '{{request.path.id}}',
  'rule.tmpl.tag.request.query': '{{request.query.q}}',
  'rule.tmpl.tag.request.header': '{{request.header.Authorization}}',
  'rule.tmpl.tag.request.body': '{{request.body.user.id}}',
  'rule.tmpl.tag.state': '{{state.token}}',
  'rule.act.stateWrites.label': 'State writes',
  'rule.act.stateWrites.helper':
    'Set state when this rule matches. Applied before the body renders, so {{state.key}} sees the new value.',
  'rule.act.stateWrites.keyPlaceholder': 'State key',
  'rule.act.stateWrites.valPlaceholder': 'Value (tags allowed)',
  'rule.act.webhook.label': 'Webhook',
  'rule.act.webhook.badge': 'Stored, not yet sent',
  'rule.act.webhook.helper': "HookBox saves this with the rule but doesn't fire it yet.",
  'rule.act.webhook.urlPlaceholder': 'https://example.com/hook',
  'rule.act.webhook.bodyPlaceholder': 'Webhook body (templated)',
  'rule.thr.intro': "Overrides the endpoint's values for requests this rule serves.",
  'rule.thr.latency.label': 'Latency',
  'rule.thr.latency.unit': 'ms',
  'rule.thr.latency.helper': '0–10000ms. Delays the response.',
  'rule.thr.rateLimit.label': 'Rate limit',
  'rule.thr.rateLimit.unit': 'req/min',
  'rule.thr.rateLimit.helper': '0 = unlimited.',
  'rule.thr.chaosMode.label': 'Chaos mode',
  'rule.thr.chaosMode.inherit': 'Inherit from endpoint',
  'rule.thr.chaosMode.error': 'Error (random 5xx)',
  'rule.thr.chaosMode.dropout': 'Dropout (drop connection)',
  'rule.error.path.invalid': 'Enter a path starting with /.',
  'rule.error.status.range': 'Status must be 100–599.',
  'rule.error.state.key.invalid': 'Keys allow letters, numbers, _ and - (max 64).',
  'rule.error.body.tooLarge': 'Response body is over the 256 KB cap.',
  'rule.footer.invalid': '{n} fields need attention',
  'rule.footer.ready': 'Ready to save',
  'rule.toast.saved': 'Rule saved.',
  'rule.toast.updated': 'Rule updated.',
  'rule.error.save': "Couldn't save the rule. Check the highlighted fields and try again.",
  'rule.error.gone': 'This rule was deleted elsewhere. Closing and refreshing.',

  // ── 5.8 Rules manager ──
  'rules.title': 'Rules',
  'rules.newRule': 'New rule',
  'rules.loading.aria': 'Loading rules',
  'rules.col.priority': 'Priority',
  'rules.col.name': 'Rule',
  'rules.col.match': 'Match',
  'rules.col.enabled': 'On',
  'rules.empty.title': 'No rules yet',
  'rules.empty.body':
    'Without a rule, unmatched requests fall through to Auto-CRUD, then your tunnel, then your proxy target, then the default response.',
  'rules.error.title': "Couldn't load rules",
  'rules.error.retry': 'Retry',
  'rules.row.menu.aria': 'Rule actions',
  'rules.row.edit': 'Edit',
  'rules.row.duplicate': 'Duplicate',
  'rules.row.delete': 'Delete',
  'rules.row.unnamed': 'Untitled rule',
  'rules.delete.title': 'Delete this rule?',
  'rules.delete.body': '"{name}" will stop matching requests. This can\'t be undone.',
  'rules.delete.confirm': 'Delete rule',
  'rules.delete.cancel': 'Cancel',
  'rules.toast.deleted': 'Rule deleted.',
  'rules.toast.duplicated': 'Rule duplicated.',
  'rules.toast.enabled': 'Rule enabled.',
  'rules.toast.disabled': 'Rule disabled.',
  'rules.error.toggle': "Couldn't update the rule. Reverted.",

  // ── 5.9 Endpoint settings ──
  'set.title': 'Settings',
  'set.loading.aria': 'Loading settings',
  'set.error.title': "Couldn't load settings",
  'set.error.retry': 'Retry',
  'set.save': 'Save',
  'set.saving': 'Saving…',
  'set.toast.saved': 'Settings saved.',
  'set.error.save': "Couldn't save. Your changes were reverted.",
  'set.identity.title': 'Identity',
  'set.identity.name.label': 'Endpoint name',
  'set.identity.name.placeholder': 'e.g. Checkout API',
  'set.identity.name.helper': 'Optional. Just a label for you.',
  'set.identity.mockUrl.label': 'Mock URL',
  'set.identity.pathUrl.label': 'Local path',
  'set.identity.token.label': 'Token',
  'set.proxy.title': 'Proxy target (MITM)',
  'set.proxy.url.label': 'Target URL',
  'set.proxy.url.placeholder': 'https://api.example.com',
  'set.proxy.url.helper':
    'Unmatched requests forward here. A matching rule always wins. Leave empty to turn off.',
  'set.proxy.url.note': 'Targets on private or loopback addresses are blocked and return 502.',
  'set.proxy.url.invalid': 'Enter an http or https URL with a host.',
  'set.crud.title': 'Auto-CRUD',
  'set.crud.toggle.label': 'Serve a REST store for unmatched requests',
  'set.crud.peek.label': 'Collections',
  'set.crud.peek.placeholder': 'Collection name',
  'set.crud.peek.view': 'View',
  'set.crud.peek.empty': 'This collection is empty.',
  'set.crud.peek.count': '{n} items',
  'set.crud.peek.invalid': 'Names allow letters, numbers, _ and - (max 64).',
  'set.crud.peek.clear': 'Clear collection',
  'set.default.title': 'Default response',
  'set.default.helper': 'What an endpoint returns when nothing else matches.',
  'set.default.mock404.label': '404 Not Found',
  'set.default.mock404.helper': 'Return 404 with a no-match body.',
  'set.default.echo.label': 'Echo',
  'set.default.echo.helper': 'Reflect the request back as JSON (method, path, query, headers, body).',
  'set.cond.title': 'Simulated conditions',
  'set.cond.helper': 'Applied in order: rate limit → chaos → latency.',
  'set.cond.latency.label': 'Latency',
  'set.cond.latency.unit': 'ms',
  'set.cond.latency.helper': '0–10000ms added before responding.',
  'set.cond.rateLimit.label': 'Rate limit',
  'set.cond.rateLimit.unit': 'req/min',
  'set.cond.rateLimit.helper': '0 = unlimited. Over the limit returns 429. Counts proxy and Auto-CRUD too.',
  'set.cond.chaos.label': 'Chaos',
  'set.cond.chaos.unit': '%',
  'set.cond.chaos.helper': 'Chance a request fails on purpose. 0 never, 100 always.',
  'set.cond.chaosMode.label': 'Chaos mode',
  'set.cond.chaosMode.error': 'Error (random 5xx)',
  'set.cond.chaosMode.dropout': 'Dropout (drop the connection)',
  'set.cors.title': 'Auto-CORS',
  'set.cors.toggle.label': 'Handle CORS automatically',
  'set.cors.helper': 'Answers OPTIONS preflight and reflects the Origin — on the mock surface only.',
  'set.retention.title': 'Retention & state',
  'set.retention.note': 'The last 100 requests per endpoint are kept for 24 hours.',
  'set.retention.clearHistory': 'Clear request history',
  'set.retention.clearState': 'Clear state',
  'set.retention.stateNote': 'State is per-endpoint and shared across all callers.',
  'set.danger.title': 'Danger zone',
  'set.danger.delete.label': 'Delete endpoint',
  'set.danger.delete.helper': 'Permanently delete this endpoint, its rules, state, and history.',
  'set.confirm.clearHistory.title': 'Clear request history?',
  'set.confirm.clearHistory.body':
    'All {n} traces for this endpoint will be removed. The live feed starts fresh.',
  'set.confirm.clearHistory.confirm': 'Clear history',
  'set.confirm.clearState.title': 'Clear endpoint state?',
  'set.confirm.clearState.body':
    "Every state key on this endpoint will be removed. Rules that require state stop matching until it's set again.",
  'set.confirm.clearState.confirm': 'Clear state',
  'set.confirm.clearCollection.title': 'Clear collection "{name}"?',
  'set.confirm.clearCollection.body':
    'Every item in this Auto-CRUD collection will be removed. This can\'t be undone.',
  'set.confirm.clearCollection.confirm': 'Clear collection',
  'set.confirm.delete.title': 'Delete endpoint {token}?',
  'set.confirm.delete.body':
    'This deletes the endpoint and everything in it — rules, state, history, and collections. The mock URL stops working. This can\'t be undone.',
  'set.confirm.delete.prompt': 'Type the token to confirm:',
  'set.confirm.delete.placeholder': '{token}',
  'set.confirm.delete.confirm': 'Delete endpoint',
  'set.confirm.cancel': 'Cancel',
  'set.toast.historyCleared': 'Request history cleared.',
  'set.toast.stateCleared': 'State cleared.',
  'set.toast.collectionCleared': 'Collection cleared.',
  'set.toast.deleted': 'Endpoint deleted.',
  'set.error.delete': "Couldn't delete the endpoint. Try again.",

  // ── 5.10 Dashboard shell states ──
  'dash.state.loading.aria': 'Loading endpoint',
  'dash.state.notFound.title': 'Endpoint not found',
  'dash.state.notFound.body':
    "This endpoint doesn't exist — it may never have, or it was deleted long ago.",
  'dash.state.gone.title': 'Endpoint deleted',
  'dash.state.gone.body': 'This endpoint was deleted. Its mock URL now returns 410.',
  'dash.state.backToStart': 'Back to start',
  'dash.state.offline.title': "You're offline",
  'dash.state.offline.body':
    "Lost the connection. Showing the last data received — we'll catch up when you're back.",

  // ── 5.11 Tunnel / CLI page ──
  'cli.title': 'Tunnel from your machine',
  'cli.intro':
    'The tunnel forwards public traffic for an endpoint to a server on your localhost — so you can test webhooks and integrations against code you\'re running right now. Tunneled requests show up in the feed labeled tunnel.',
  'cli.command.label': 'Run this',
  'cli.command.template':
    'tunnel --port {port} --endpoint {token} --secret {secret} --host {host}',
  'cli.command.portDefault': '3000',
  'cli.command.copy.aria': 'Copy tunnel command',
  'cli.secret.reveal': 'Reveal secret',
  'cli.secret.hide': 'Hide secret',
  'cli.secret.warning':
    "This is your owner capability — your secret. Anyone who has it controls this endpoint. Don't paste it into shared terminals, screenshots, or issues.",
  'cli.behavior.title': 'What to expect',
  'cli.behavior.order':
    'In the resolution order, the tunnel is tried after Auto-CRUD and before your proxy target.',
  'cli.behavior.noTunnel':
    "When nothing is connected, tunneled paths return 504 no_tunnel — that's expected, not a bug.",
  'cli.behavior.takeover':
    'Only one tunnel binds at a time. Connect a second and it takes over; the first is dropped with "rebound elsewhere."',
  'cli.behavior.reconnect':
    "If the connection drops, the CLI reconnects with backoff. Bad credentials stop it — it won't retry into a wall.",
  'cli.toast.copied': 'Copied.',

  // ── 5.13 Global toasts & shared ──
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.copy.announce': 'Copied to clipboard',
  'common.retry': 'Retry',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.close.aria': 'Close',
  'common.dismiss': 'Dismiss',
  'common.error.401':
    'Your session ended — your secret was rotated somewhere else. Enter your email to continue.',
  'common.error.network': 'Network error. Check your connection and try again.',
  'common.error.generic': 'Something went wrong. Try again.',
  'common.notFound.title': 'Page not found',
  'common.notFound.body': "That page doesn't exist.",
  'common.notFound.home': 'Back to start',
} as const

export type CopyKey = keyof typeof copy

/** Resolve a copy key, substituting {slot} interpolation values. */
export function t(key: CopyKey, vars?: Record<string, string | number>): string {
  let s: string = copy[key]
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replaceAll(`{${k}}`, String(v))
    }
  }
  return s
}
